plugins {
    id 'idea'
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.147'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

neoForge {
    version = neo_version
    runs {
        client {
            client()
            gameDirectory = project.file('runs/client')
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(ProcessResources).configureEach {
    def properties = [minecraft_version: minecraft_version, mod_id: mod_id,
                      mod_name: mod_name, mod_license: mod_license,
                      mod_version: mod_version, mod_authors: mod_authors,
                      mod_description: mod_description]
    inputs.properties properties
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand properties
    }
}
