org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.12.101-hotspot
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
neo_version=21.1.248
mod_id=worldeditwandfabrication
mod_name=WorldEdit Wand Fabrication
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.nitricacid.worldeditwandfabrication
mod_authors=NitricAcid
mod_description=Restores the WorldEdit Items Wand Axe in creative mode.
